language: rust

# qmlrs needs the Ubuntu 14.04 trusty beta image to get a recent Qt5 (trusty ships with Qt 5.2)
# the trusty beta is only available as sudo
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      rust: stable
    - os: linux
      dist: trusty
      sudo: required
      rust: beta
    - os: linux
      dist: trusty
      sudo: required
      rust: nightly
    - os: osx
      rust: stable
    - os: osx
      rust: beta
    - os: osx
      rust: nightly
  allow_failures:
    - rust: nightly

install:
  - ./travis/install.sh

# travis-cargo is a wrapper around cargo we use for code coverage generation
# https://github.com/huonw/travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - cargo build --verbose
  - cargo build --verbose --example factorial
  - cargo build --verbose --example factorial_string
  - cargo build --verbose --example multiply
  # this is to stop cargo from hiding stdout of tests, useful when strange things happen and tests run forever.
  # cargo test -- --nocapture
  - cargo test --verbose
  - cargo bench --verbose

after_success:
  # measure code coverage and upload to coveralls.io
  - travis-cargo coveralls --no-sudo --verify
